apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
spec:
  selector:
    matchLabels:
      run: my-service
  replicas: 2
  template:
    metadata:
      labels:
        run: my-service
    spec:
      containers:
      - name: my-service
        image: jasseralg/service
        ports:
        - containerPort: 3000