apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    run: my-service
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30475 # the port exposed 
    port: 3000 # Some times your application inside container serves different services on a different port.
    targetPort: 3000 # This is the actual port on which your application is running inside the container.
    protocol: TCP
    
  selector:
    run: my-service
